param([Parameter(Mandatory)][string]$AgentId,[string]$AutomationRoot="D:\SoulHunter-Automation",[string]$StatusPath="",[string]$RegisterPath="",[string]$StatePath="")
$ErrorActionPreference='Stop'
Import-Module (Join-Path (Split-Path $PSScriptRoot -Parent) 'LiveQuotaProbe.psm1') -Force
$QuotaRoot=Join-Path $AutomationRoot 'Quota';$AgentRoot=Join-Path $AutomationRoot 'Agents'
if([string]::IsNullOrWhiteSpace($StatusPath)){$StatusPath=Join-Path $QuotaRoot ('quota-check-'+($AgentId -replace '[^A-Za-z0-9._-]','_')+'.json')}
if([string]::IsNullOrWhiteSpace($RegisterPath)){$RegisterPath=Join-Path $AgentRoot 'Agent-Register.json'}
if([string]::IsNullOrWhiteSpace($StatePath)){$StatePath=Join-Path $AgentRoot 'Agent-State.json'}
New-Item -ItemType Directory -Path $QuotaRoot -Force|Out-Null;New-Item -ItemType Directory -Path $AgentRoot -Force|Out-Null
function Save-Json($Path,$Obj){$tmp="$Path.tmp";($Obj|ConvertTo-Json -Depth 30)|Set-Content -LiteralPath $tmp -Encoding UTF8;Move-Item -LiteralPath $tmp -Destination $Path -Force}
function Read-Json($Path){if(!(Test-Path -LiteralPath $Path)){return $null};try{return Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json -ErrorAction Stop}catch{return $null}}
function Get-RegisteredAgent([string]$Id){$reg=Read-Json $RegisterPath;if($null -eq $reg -or $null -eq $reg.agents){return $null};foreach($a in @($reg.agents)){if([string]$a.agent_id -eq $Id){return $a}};return $null}
$registered=Get-RegisteredAgent $AgentId;$now=(Get-Date).ToUniversalTime().ToString('o')
if($null -eq $registered){$record=[ordered]@{agent_id=$AgentId;provider='';model_id='';quota_scope='unknown';pool_id='';five_hour_remaining_percent=$null;weekly_remaining_percent=$null;remaining_percent=$null;effective_remaining_percent=$null;reserve_percent=25;usable_remaining_percent=0;verified=$false;status='UNREGISTERED';reason='Agent is not present in manual Agent-Register.json.';quota_source='none';fetched_at=$now;reset_at=''};$top=[ordered]@{schema='soul-hunter.quota-status.v3';generated_at=$now;verified=$false;status='UNREGISTERED';error=$record.reason;record=$record};Save-Json $StatusPath $top;exit 2}
$provider=[string]$registered.provider;$model='';if(@($registered.models).Count -gt 0){$model=[string]@($registered.models)[0]}
if($AgentId -eq 'Codex'){$q=Get-LiveCodexQuotaEvidence -CodexExecutable 'C:\Users\Lenovo\AppData\Local\Programs\OpenAI\Codex\bin\codex.exe'}
elseif($AgentId -like 'AGY/*'){$family=$AgentId.Substring(4);$q=Get-LiveAGYQuotaEvidence;if($q.Success){$want=if($family -eq 'Gemini'){'Gemini'}else{'ThirdParty'};$r=$q.Models|Where-Object {$_.family -eq $want}|Select-Object -First 1;if($null -eq $r){$q=[pscustomobject]@{Success=$false;Error="Live AGY source answered, but no quota family matched $AgentId."}}else{$q=[pscustomobject]@{Success=$true;Row=[pscustomobject]@{model_id=$model;remaining_percent=$r.remaining_percent;reset_time=$r.reset_time;quota_scope=$r.quota_scope;pool_id=$r.pool_id;five_hour=$r.five_hour;weekly=$r.weekly;source=$r.source};FetchedAt=$r.fetched_at}}}}
else{$q=[pscustomobject]@{Success=$false;Error='This agent is not quota-bearing.'}}
if($q.Success){$r=$q.Row;$wins=@($r.five_hour,$r.weekly)|Where-Object {$null -ne $_};$remaining=[double]$r.remaining_percent;if($wins.Count -gt 0){$remaining=[double](($wins|Measure-Object -Minimum).Minimum)};$remaining=[math]::Max(0,[math]::Min(100,$remaining));$status=if($remaining -le 0){'QUOTA_EXHAUSTED'}else{'AVAILABLE'};$usable=[math]::Floor($remaining*.75);$record=[ordered]@{agent_id=$AgentId;provider=$provider;model_id=[string]$r.model_id;quota_scope=[string]$r.quota_scope;pool_id=[string]$r.pool_id;five_hour_remaining_percent=$r.five_hour;weekly_remaining_percent=$r.weekly;remaining_percent=$remaining;effective_remaining_percent=$remaining;reserve_percent=25;usable_remaining_percent=$usable;verified=$true;status=$status;reason='Live read-only quota evidence';quota_source=[string]$r.source;fetched_at=[string]$q.FetchedAt;reset_at=[string]$r.reset_time}}else{$record=[ordered]@{agent_id=$AgentId;provider=$provider;model_id=$model;quota_scope='unknown';pool_id='';five_hour_remaining_percent=$null;weekly_remaining_percent=$null;remaining_percent=$null;effective_remaining_percent=$null;reserve_percent=25;usable_remaining_percent=0;verified=$false;status='UNVERIFIED';reason=[string]$q.Error;quota_source='none';fetched_at=$now;reset_at=''}}
$top=[ordered]@{schema='soul-hunter.quota-status.v3';generated_at=$now;verified=[bool]$record.verified;status=[string]$record.status;error=$(if($record.verified){''}else{[string]$record.reason});record=$record};Save-Json $StatusPath $top
$state=[ordered]@{schema='soul-hunter.agent-state.v3';updated_at=$now;agents=@{}};$old=Read-Json $StatePath;if($old -and $old.agents){foreach($p in @($old.agents.PSObject.Properties)){$state.agents[$p.Name]=$p.Value}}
$base=[ordered]@{agent_id=$AgentId;name=[string]$registered.name;provider=$provider;kind=[string]$registered.kind;models=@($registered.models);capabilities=@($registered.capabilities);tools=@($registered.tools);priority=$registered.priority;enabled=[bool]$registered.enabled}
$oldAgent=$state.agents[$AgentId];if($oldAgent){foreach($p in @($oldAgent.PSObject.Properties)){if($base.Keys -notcontains $p.Name){$base[$p.Name]=$p.Value}}}
$base['runtime']=[ordered]@{status=$record.status;health=$(if($record.verified -and $record.status -eq 'AVAILABLE'){'AVAILABLE'}else{'BLOCKED'});quota_verified=[bool]$record.verified;quota_scope=$record.quota_scope;pool_id=$record.pool_id;five_hour_remaining_percent=$record.five_hour_remaining_percent;weekly_remaining_percent=$record.weekly_remaining_percent;remaining_percent=$record.remaining_percent;usable_remaining_percent=$record.usable_remaining_percent;reset_at=$record.reset_at;quota_source=$record.quota_source;last_checked=$record.fetched_at;reason=$record.reason}
$state.agents[$AgentId]=[pscustomobject]$base;Save-Json $StatePath $state
Write-Host ("QUOTA REPORT: {0} status={1} verified={2} remaining={3}% usable={4}% scope={5} pool={6} reset={7}" -f $AgentId,$record.status,$record.verified,$record.remaining_percent,$record.usable_remaining_percent,$record.quota_scope,$record.pool_id,$record.reset_at)
if(!$record.verified){exit 2};if($record.status -eq 'QUOTA_EXHAUSTED'){exit 3};exit 0

