UnityEditor.EditorApplication.isPaused=false;UnityEngine.Application.runInBackground=true;
var player=UnityEngine.Object.FindFirstObjectByType<SoulHunter.Gameplay.Player.PlayerController>();
var xp=player.GetComponent<SoulHunter.Gameplay.Player.PlayerExperience>();
xp.AddXP(xp.XPToNextLevel-xp.CurrentXP);
var buttons=UnityEngine.Object.FindObjectsByType<UnityEngine.UI.Button>(UnityEngine.FindObjectsSortMode.None).Where(b=>b.name.StartsWith("Upgrade_Button_")).ToArray();
bool paused=UnityEngine.Time.timeScale==0;
if(buttons.Length>0)buttons[0].onClick.Invoke();
UnityEngine.InputSystem.InputSystem.QueueStateEvent(UnityEngine.InputSystem.Keyboard.current,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.D));
UnityEngine.ScreenCapture.CaptureScreenshot("Logs/RecoveredGameplay.png");
return new {level=xp.CurrentLevel,upgradePaused=paused,choices=buttons.Length,resumed=UnityEngine.Time.timeScale==1,position=player.transform.position.ToString(),sprite=player.GetComponentInChildren<UnityEngine.SpriteRenderer>()?.sprite?.name};
