var scene = UnityEditor.SceneManagement.EditorSceneManager.NewPreviewScene();
var root = new UnityEngine.GameObject("EvolutionRequirementsTest");
UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(root, scene);
var flags = System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic;
var evo = UnityEngine.ScriptableObject.CreateInstance<SoulHunter.Gameplay.Combat.WeaponEvolutionData>();
var union = UnityEngine.ScriptableObject.CreateInstance<SoulHunter.Gameplay.Combat.WeaponUnionData>();
var checks = new System.Collections.Generic.List<string>();
try {
    var manager = root.AddComponent<SoulHunter.Gameplay.Combat.WeaponManager>();
    var levels = (System.Collections.Generic.Dictionary<SoulHunter.Gameplay.Combat.UpgradeData.UpgradeType,int>)manager.GetType().GetField("_weaponLevels",flags).GetValue(manager);
    evo.BaseWeapon = SoulHunter.Gameplay.Combat.UpgradeData.UpgradeType.Laurel;
    evo.BaseWeaponMaxLevel = 7;
    evo.RequiredPassive = SoulHunter.Gameplay.Combat.UpgradeData.UpgradeType.Armor;
    evo.RequiredPassiveMaxLevel = 9;
    evo.AdditionalPassives = new [] {new SoulHunter.Gameplay.Combat.PassiveEvolutionRequirement {Type=SoulHunter.Gameplay.Combat.UpgradeData.UpgradeType.Spinach,MinimumLevel=9}};
    levels[evo.BaseWeapon]=7; levels[evo.RequiredPassive]=9;
    if(evo.RequirementsMet(manager)) throw new System.Exception("Missing second passive accepted");
    checks.Add("missing second passive rejected");
    levels[evo.AdditionalPassives[0].Type]=8;
    if(evo.RequirementsMet(manager)) throw new System.Exception("Underlevel passive accepted");
    checks.Add("underlevel second passive rejected");
    levels[evo.AdditionalPassives[0].Type]=9;
    if(!evo.RequirementsMet(manager)) throw new System.Exception("Complete requirements rejected");
    checks.Add("both max-level prerequisites accepted");
    levels[evo.BaseWeapon]=6;
    if(evo.RequirementsMet(manager)) throw new System.Exception("Underlevel weapon accepted");
    levels[evo.BaseWeapon]=7;
    checks.Add("underlevel weapon rejected");
    evo.AdditionalPassives=null;
    if(!evo.RequirementsMet(manager)) throw new System.Exception("Legacy data broken");
    checks.Add("legacy single-passive data supported");
    manager.GetType().GetField("_availableEvolutions",flags).SetValue(manager,new System.Collections.Generic.List<SoulHunter.Gameplay.Combat.WeaponEvolutionData>{evo});
    string name;
    if(manager.TryEvolveWeapon(out name) || name!="") throw new System.Exception("Missing result consumed evolution");
    checks.Add("missing evolution prefab rejected");
    var result = new UnityEngine.GameObject("EvolutionResult"); result.transform.SetParent(root.transform);
    evo.EvolvedWeaponPrefab=result; evo.EvolvedName="Test Evolution";
    if(!manager.TryEvolveWeapon(out name) || name!=evo.EvolvedName) throw new System.Exception("Failed attempt poisoned retry");
    if(manager.TryEvolveWeapon(out name)) throw new System.Exception("Duplicate evolution accepted");
    checks.Add("retry succeeds once after fixing result");
    union.WeaponA=SoulHunter.Gameplay.Combat.UpgradeData.UpgradeType.Whip;
    union.WeaponB=SoulHunter.Gameplay.Combat.UpgradeData.UpgradeType.Axe;
    levels[union.WeaponA]=union.WeaponAMaxLevel; levels[union.WeaponB]=union.WeaponBMaxLevel;
    manager.GetType().GetField("_availableUnions",flags).SetValue(manager,new System.Collections.Generic.List<SoulHunter.Gameplay.Combat.WeaponUnionData>{union});
    int before=manager.GetActiveWeaponsCount();
    if(manager.TryEvolveWeapon(out name) || manager.GetActiveWeaponsCount()!=before) throw new System.Exception("Missing union result changed slots");
    checks.Add("missing union prefab preserves inventory");
    union.UnionWeaponPrefab=result;
    if(!manager.TryEvolveWeapon(out name) || manager.GetActiveWeaponsCount()!=before-1) throw new System.Exception("Union retry/slots failed");
    checks.Add("union retry and slot accounting");
    evo.BaseWeapon=union.WeaponB; evo.BaseWeaponMaxLevel=1;
    if(manager.TryEvolveWeapon(out name)) throw new System.Exception("Consumed union weapon evolved again");
    checks.Add("consumed union weapon cannot evolve again");
    return new {passed=checks.Count,checks};
} finally {
    UnityEngine.Object.DestroyImmediate(root);
    UnityEngine.Object.DestroyImmediate(evo); UnityEngine.Object.DestroyImmediate(union);
    UnityEditor.SceneManagement.EditorSceneManager.ClosePreviewScene(scene);
}
