var scene=UnityEditor.SceneManagement.EditorSceneManager.NewPreviewScene();
var root=new UnityEngine.GameObject("ShroudTest");
UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(root,scene);
var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
int checks=0;
try {
 var health=root.AddComponent<SoulHunter.Gameplay.Combat.HealthController>();health.Initialize(100);health.KnockbackResistance=1;
 var stats=root.AddComponent<SoulHunter.Gameplay.Player.PlayerStats>();
 var prefab=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.GameObject>("Assets/Prefabs/Weapons/Generated/CrimsonShroud.prefab");
 var host=UnityEngine.Object.Instantiate(prefab,root.transform);
 var shield=host.GetComponent<SoulHunter.Gameplay.Combat.CrimsonShroudWeapon>();
 typeof(SoulHunter.Gameplay.Combat.LaurelWeapon).GetMethod("Awake",flags).Invoke(shield,null);
 shield.GetType().GetMethod("OnEnable",flags).Invoke(shield,null);
 var tick=typeof(SoulHunter.Gameplay.Combat.LaurelWeapon).GetMethod("AdvanceTime",flags);
 var pulse=shield.GetType().GetMethod("AdvanceRetaliation",flags);
 if(shield.CurrentCharges!=3 || shield.BaseRechargeCooldown!=8 || shield.BlockGraceSeconds!=1)throw new System.Exception("Baseline");checks++;
 shield.LevelUp();if(shield.CurrentLevel!=1)throw new System.Exception("Level cap");checks++;
 var hit=new SoulHunter.Gameplay.Combat.DamagePacket(999,UnityEngine.Vector3.zero,UnityEngine.Vector3.zero);
 health.TakeDamage(hit);health.TakeDamage(hit);
 if(health.CurrentHealth!=100 || shield.CurrentCharges!=2 || shield.PendingPulses!=1)throw new System.Exception("Grace/charge");checks++;
 tick.Invoke(shield,new object[]{1.1f});health.TakeDamage(hit);
 tick.Invoke(shield,new object[]{1.1f});health.TakeDamage(hit);
 tick.Invoke(shield,new object[]{1.1f});health.TakeDamage(hit);
 if(health.CurrentHealth!=90 || shield.CurrentCharges!=0 || shield.PendingPulses!=3)throw new System.Exception("Exhausted cap");checks++;
 health.TakeDamage(new SoulHunter.Gameplay.Combat.DamagePacket(3,UnityEngine.Vector3.zero,UnityEngine.Vector3.zero));
 if(health.CurrentHealth!=87)throw new System.Exception("Small hit amplified");checks++;
 if(shield.CalculateRetaliationDamage(999)!=100)throw new System.Exception("Raw damage cap");checks++;
 stats.AddMight(1);stats.AddCurse(0.5f);stats.AddArmor(5);
 if(shield.CalculateRetaliationDamage(100)!=450)throw new System.Exception("Stat scaling");checks++;
 var near=new UnityEngine.GameObject("Near");near.transform.SetParent(root.transform);near.transform.localPosition=UnityEngine.Vector3.right;
 var nearHealth=near.AddComponent<SoulHunter.Gameplay.Combat.HealthController>();nearHealth.Initialize(1000);nearHealth.KnockbackResistance=1;
 var nearEnemy=near.AddComponent<SoulHunter.Gameplay.AI.EnemyController>();
 var far=new UnityEngine.GameObject("Far");far.transform.SetParent(root.transform);far.transform.localPosition=UnityEngine.Vector3.right*20;
 var farHealth=far.AddComponent<SoulHunter.Gameplay.Combat.HealthController>();farHealth.Initialize(1000);farHealth.KnockbackResistance=1;
 var farEnemy=far.AddComponent<SoulHunter.Gameplay.AI.EnemyController>();
 if(!SoulHunter.Gameplay.AI.EnemyController.ActiveEnemies.Contains(nearEnemy))SoulHunter.Gameplay.AI.EnemyController.ActiveEnemies.Add(nearEnemy);
 if(!SoulHunter.Gameplay.AI.EnemyController.ActiveEnemies.Contains(farEnemy))SoulHunter.Gameplay.AI.EnemyController.ActiveEnemies.Add(farEnemy);
 int pulses=0;shield.OnRetaliation+=d=>pulses++;
 pulse.Invoke(shield,new object[]{0f});if(pulses!=0)throw new System.Exception("Pause");checks++;
 pulse.Invoke(shield,new object[]{0.001f});if(pulses!=1 || shield.PendingPulses!=2)throw new System.Exception("First pulse");
 pulse.Invoke(shield,new object[]{0.05f});if(pulses!=1)throw new System.Exception("Interval");checks++;
 pulse.Invoke(shield,new object[]{0.2f});if(pulses!=3 || shield.PendingPulses!=0)throw new System.Exception("Queue drain");checks++;
 if(nearHealth.CurrentHealth!=700 || farHealth.CurrentHealth!=1000)throw new System.Exception("Retaliation targeting/damage");checks++;
 SoulHunter.Gameplay.AI.EnemyController.ActiveEnemies.Remove(nearEnemy);SoulHunter.Gameplay.AI.EnemyController.ActiveEnemies.Remove(farEnemy);
 stats.ReduceCooldown(0.5f);tick.Invoke(shield,new object[]{2.36f});if(shield.CurrentCharges!=1)throw new System.Exception("Recharge");checks++;
 stats.AddAmount(999);health.TakeDamage(hit);if(shield.PendingPulses!=50)throw new System.Exception("Bounded Amount");checks++;
 shield.GetType().GetMethod("OnDisable",flags).Invoke(shield,null);
 if(health.DamageModifier!=null || health.DamageInterceptor!=null || shield.PendingPulses!=0)throw new System.Exception("Cleanup");checks++;
 health.TakeDamage(new SoulHunter.Gameplay.Combat.DamagePacket(20,UnityEngine.Vector3.zero,UnityEngine.Vector3.zero));
 if(health.CurrentHealth!=67)throw new System.Exception("Stale cap");checks++;
 return new{passed=checks};
}finally{UnityEngine.Object.DestroyImmediate(root);UnityEditor.SceneManagement.EditorSceneManager.ClosePreviewScene(scene);}
