if(!UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Play required");
var player=UnityEngine.Object.FindFirstObjectByType<SoulHunter.Gameplay.Player.PlayerController>();
var ui=UnityEngine.Object.FindFirstObjectByType<SoulHunter.Gameplay.UI.ChestUI>();
if(player==null||ui==null)throw new System.Exception("Gameplay not ready");
var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
var button=(UnityEngine.UI.Button)ui.GetType().GetField("_claimButton",flags).GetValue(ui);
var label=(TMPro.TextMeshProUGUI)ui.GetType().GetField("_rewardText",flags).GetValue(ui);
var prefab=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.GameObject>("Assets/Prefabs/Items/Chest.prefab");
var first=UnityEngine.Object.Instantiate(prefab,player.transform.position,UnityEngine.Quaternion.identity);
var second=UnityEngine.Object.Instantiate(prefab,player.transform.position,UnityEngine.Quaternion.identity);
var tick=typeof(SoulHunter.Gameplay.Pickups.ChestPickup).GetMethod("Update",flags);
int checks=0;
try {
 UnityEngine.Time.timeScale=1;UnityEngine.Physics.SyncTransforms();
 tick.Invoke(first.GetComponent<SoulHunter.Gameplay.Pickups.ChestPickup>(),null);
 if(first.activeSelf||UnityEngine.Time.timeScale!=0)throw new System.Exception("First chest failed");checks++;
 string initial=label.text;
 tick.Invoke(second.GetComponent<SoulHunter.Gameplay.Pickups.ChestPickup>(),null);
 if(!second.activeSelf||label.text!=initial)throw new System.Exception("Second chest consumed/overwrote reward while modal open");checks++;
 button.onClick.Invoke();
 tick.Invoke(second.GetComponent<SoulHunter.Gameplay.Pickups.ChestPickup>(),null);
 if(second.activeSelf||UnityEngine.Time.timeScale!=0)throw new System.Exception("Second chest not collected after claim");checks++;
 button.onClick.Invoke();
 first.GetComponent<SoulHunter.Gameplay.Pickups.ChestPickup>().ResetPickup();first.SetActive(true);
 tick.Invoke(first.GetComponent<SoulHunter.Gameplay.Pickups.ChestPickup>(),null);
 if(first.activeSelf||UnityEngine.Time.timeScale!=0)throw new System.Exception("Reused chest failed");checks++;
 button.onClick.Invoke();
 var poolManager=SoulHunter.Gameplay.Pickups.PickupPoolManager.Instance;
 var pool=(System.Collections.Generic.Stack<UnityEngine.GameObject>)poolManager.GetType().GetField("_chestPool",flags).GetValue(poolManager);
 if(pool.Count==0)throw new System.Exception("Expected prewarmed chest pool");
 var pooled=pool.Peek();int count=pool.Count;
 poolManager.SpawnChest(player.transform.position);UnityEngine.Physics.SyncTransforms();
 tick.Invoke(pooled.GetComponent<SoulHunter.Gameplay.Pickups.ChestPickup>(),null);
 if(pooled.activeSelf||pool.Count!=count||pool.Peek()!=pooled)throw new System.Exception("Pool return failed");checks++;
 button.onClick.Invoke();poolManager.SpawnChest(player.transform.position);UnityEngine.Physics.SyncTransforms();
 tick.Invoke(pooled.GetComponent<SoulHunter.Gameplay.Pickups.ChestPickup>(),null);
 if(pooled.activeSelf||pool.Count!=count||UnityEngine.Time.timeScale!=0)throw new System.Exception("Pool reuse/reset failed");checks++;
 button.onClick.Invoke();
 var result=new{passed=true,checks};System.IO.File.WriteAllText("Logs/SequentialChestVerification.json",Newtonsoft.Json.JsonConvert.SerializeObject(result));return result;
}finally{button.onClick.Invoke();UnityEngine.Object.Destroy(first);UnityEngine.Object.Destroy(second);}
